#!/bin/bash
#
#
#BAR TIME


dwm_cmus () {
    SEP1="["
    if ps -C cmus > /dev/null; then
        ARTIST=$(cmus-remote -Q | grep -a '^tag artist' | awk '{gsub("tag artist ", "");print}')
        TRACK=$(cmus-remote -Q | grep -a '^tag title' | awk '{gsub("tag title ", "");print}')
        POSITION=$(cmus-remote -Q | grep -a '^position' | awk '{gsub("position ", "");print}')
        DURATION=$(cmus-remote -Q | grep -a '^duration' | awk '{gsub("duration ", "");print}')
        STATUS=$(cmus-remote -Q | grep -a '^status' | awk '{gsub("status ", "");print}')
        SHUFFLE=$(cmus-remote -Q | grep -a '^set shuffle' | awk '{gsub("set shuffle ", "");print}')

        if [ ${#TRACK} -gt 8 ]; then
            TRACK="$(printf "%s" "$TRACK" | cut -c1-12)…"
        fi

        if [ ${#ARTIST} -gt 8 ]; then
            ARTIST="$(printf "%s" "$ARTIST" | cut -c1-12)…"
        fi

        if [ "$STATUS" = "playing" ]; then
            STATUS=""
        else
            STATUS=""
        fi

        if [ "$SHUFFLE" = "true" ]; then
            SHUFFLE=" "
        else
            SHUFFLE=""
        fi

        printf "%s%s %s - %s " "$SEP1" "$STATUS" "$ARTIST" "$TRACK"
        printf "%0d:%02d/" $((POSITION%3600/60)) $((POSITION%60))
        printf "%0d:%02d" $((DURATION%3600/60)) $((DURATION%60))
        printf "%s%s\n" "$SHUFFLE" "]"
    fi
}


mem() {
  printf " "
  printf "$(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)"
}


clock() {
	printf "| 󱑆 "
	printf "$(date '+%H:%M')"
}

while true; do
  sleep 1 && xsetroot -name "$(dwm_cmus) $(mem) $(clock)"
done &

setxkbmap -option ctrl:nocaps
WALL=$(ls $HOME/.local/wall | shuf -n 1)
WALL=$HOME/.local/wall/$WALL
feh --bg-fill $WALL --no-fehbg
picom -b --corner-radius 5 --backend glx
xss-lock -- slock &
xset r rate 200 35
dunst &
exec dwm 
