#!/bin/bash

while true; do
   xsetroot -name "$(date '+[%a,%d-%b][%I:%M]')"
   sleep 1
done &


setxkbmap -option ctrl:nocaps
WALL=$(ls /home/taras/.local/wall | shuf -n 1)
WALL=/home/taras/.local/wall/$WALL
feh --bg-fill $WALL --no-fehbg
wal -i $WALL --cols16 -n
picom -b --corner-radius 10
dunst &
xss-lock -- slock &
xset r rate 200 35
exec dwm 

