#!/bin/bash


while true; do
   xsetroot -name "$(date '+[%a,%d-%b][%I:%M]')"
   sleep 1
done &


setxkbmap -option ctrl:nocaps
#feh --bg-center /home/taras/.local/wall/wall7.png
wal -i /home/taras/.local/wall
picom -b
xss-lock -- slock &
exec dwm 

